# Generated by Django 3.1.7 on 2021-04-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20210405_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='vote',
            new_name='voter',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='vote',
            new_name='voter',
        ),
    ]
